# Requests the robot to drive around an obstacle at a given radius.
# Returns the vertices of the obstacle.

float64 obstaclePosX
float64 obstaclePosY
float64 circlingRadius
---
uint8 success
float64[] lats
float64[] lngs
